# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-07 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='ingrediente',
        ),
        migrations.AddField(
            model_name='receita',
            name='ingrediente',
            field=models.ManyToManyField(blank=True, null=True, to='receitas.Ingrediente'),
        ),
        migrations.RemoveField(
            model_name='receita',
            name='modo_preparo',
        ),
        migrations.AddField(
            model_name='receita',
            name='modo_preparo',
            field=models.ManyToManyField(blank=True, null=True, to='receitas.Preparo'),
        ),
    ]
